### ISSUE TITLE
Bugs in code for data preparation 

### ISSUE THREAD

**Issue by schellmi42** [leoshine/Spherical_Regression#5]
Hello,
I found some bugs in your data preparation code:

I followed the data preparation instructions, although it provided me with some errors:
in the build_imdb.py the fn_pattern is set to '.jpg' although some images are '.JPEG', so i changed these lines to make it work.
```
 image_file = os.path.join(src_img_dir, fo, '%s.%s' % (imgID, fn_pattern.strip('.')))
                if os.path.exists(image_file[:-4]+'.JPEG'):
                    image_file = image_file[:-4]+'.JPEG'
                assert os.path.exists(image_file), image_file
```

Also in imdb.py the line 
`imdb.close()`
calls a non-existent function, as it is not implemented in lmdb_utils. 

I just commented it out and it run through?

Lastly, when running the
` bash prepare_r4cnn.sh`
it tells me:
```

  File "prepare_r4cnn_syn_data.py", line 14, in <module>
    from lmdb_util import NpyData_lmdb, ImageData_lmdb
ImportError: cannot import name NpyData_lmdb
```
as this name is not implemented in the imagedata_lmdb.py in the imdb_util directory.
As it is not used I just removed it.

I would be happy If you could tell me if I changed something important or if the data should be correct now.

Thank you in advance

**Comment by leoshine** [comment]
Oh. Sorry. Please remove all "NpyData_lmdb" from import, it's not used and thus I didn't release.

I'll update the code.

Thanks.

**Comment by schellmi42** [comment]
Thank you, that helped!

**Comment by leoshine** [comment]
Fixed.
