### ISSUE TITLE
prepare_r4cnn freezes

### ISSUE THREAD

**Issue by schellmi42** [leoshine/Spherical_Regression#6]
Hello,

I am still stuck on the data preparation,
I tried running 
`bash prepare_r4cnn.sh`
 twice now, but for some reason it just freezes while creating the .pkl files in 'SynImages_r4cnn.cache/obj_anno_db' folder. 
One time it happened at motorbike.pkl and one time at bottle.pkl. 
It does not throw an error or terminate.
I let it run overnight just to make sure and also checked to have enough free disk space and RAM, but it just seems to freeze.

Thank you in advance!

**Comment by leoshine** [comment]
Can you confirm that you got froze at:

https://github.com/leoshine/Spherical_Regression/blob/08760b775920f46b5d6380f929406d0cbe55c71b/dataset/Pascal3D/prepare_data/prepare_r4cnn_syn_data.py#L203-L205

(?)

Basically here I'm trying to create annotation file "{category}.pkl" for each category,
and I used 12 cores to accelerate.

I doubt your multiprocessing module froze.
My suggestion is to use avoid use multiprocessing, and sequentially build up these files (just by uncomment these lines:)

https://github.com/leoshine/Spherical_Regression/blob/08760b775920f46b5d6380f929406d0cbe55c71b/dataset/Pascal3D/prepare_data/prepare_r4cnn_syn_data.py#L200-L201

Or reduce the core parameter that matches your machine:
For example:

```
from multiprocessing import Pool, cpu_count
pool = Pool(cpu_count())
pool.map(gen_anno_db, categories)
```

**Comment by schellmi42** [comment]
Thank you for your answer

The imgID2size.pkl is there, so I think  build_db and read_image_size finished.

When running with multiprocessing it just stops at some point.

When running without multiprocessing I get
  File "prepare_r4cnn_syn_data.py", line 202, in <module>
    gen_anno_db(cate, MAX_STRING_LEN=64)
  File "prepare_r4cnn_syn_data.py", line 126, in gen_anno_db
    h,w = imgID2size[imgID]
KeyError: '02691156_b97b9cde30c23b4d71d03b466c72ce41_a323_e-13_t-06_d002'
`

I guess I have to run build_db again?

**Comment by leoshine** [comment]
I'm not sure if your 'build_db' and 'read_image_size' finished normally.

Can you try following:

```
>>> import pickle
>>> imgID2size = pickle.load(open('SynImages_r4cnn.cache/ImageData_gtbox_crop.Rawpng.lmdb/imgID2size.pkl','rb'))
>>> len(imgID2size.keys())
2381106
>>> imgID2size['02691156_b97b9cde30c23b4d71d03b466c72ce41_a323_e-13_t-06_d002']
(79, 165)
```

As you can see, I got 2381106 keys(images) in the DB. 
And I can also retrieve key: '02691156_b97b9cde30c23b4d71d03b466c72ce41_a323_e-13_t-06_d002' from dictionary.

Please confirm above. (Also check if your download is complete?)
Otherwise, you may need run this two lines again:

https://github.com/leoshine/Spherical_Regression/blob/1bc9a965f3617774a907808cce2436c71b3aef62/dataset/Pascal3D/prepare_data/prepare_r4cnn_syn_data.py#L195-L197

**Comment by schellmi42** [comment]
I cannot retrieve the key from the dictionary.
As you suggested I will  run the lines again and check the dictionary afterwards.

Thank you very much!

**Comment by leoshine** [comment]
And how many keys you can get in your dict?

**Comment by schellmi42** [comment]
I have rerun the build_db and now the data preparation seems to work fine.

But now, when I want to run
`bash trainval.sh 0 --net_arch=resnet101'
I get the following error:
```
  File "trainval_workdir.py", line 128, in <module>
    dataset_train = _dataset_module( 'train', cates=opt.cates, **dataset_kwargs) #
  File "Dataset_Base.py", line 280, in __init__
    self.keys, self.recs = get_keys_recs_v1(self.cates, collection, filter=collection2filter[collection], sampling=sampling)
  File "Dataset_Base.py", line 86, in get_keys_recs_v1
    if obj_tb_pascal3d.keys[i].startswith('n'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

```

Thank you in advance!

**Comment by schellmi42** [comment]
Hello,

The data preparation runs through now, but when trying to run the training I get a FileNotFoundError for
`/dataset/Pascal3D/anno_db_v2/data.cache/objId2gtbox/cate12_train.all.pkl`
also the folder objId2ftbox is completely empty.

I tried running the prepare_Pascal3D.sh again, but that did not help.

Thank you in advance!

**Comment by leoshine** [comment]
Thanks for reporting and information.

There are a few bad annotations in Pascal3D+ (inside the .mat they provided), where the bounding box [(x1,y1), (x2,y2)] violate the constraint x1<x2 and y1<y2.

```
   (x1,y1) ----------------------+
      |                          |
      |                          |
      |                          |
      +------------------------(x2,y2)     
```
e.g.   x1, y1, x2, y2 = 464, 218, 328, 262   is an bad annotation.

For some reason, I mannually corrected their "*.mat" annotation files and forget to mention it.

I'm working on fixing this bug and I'll update you soon.

**Comment by schellmi42** [comment]
Thank you for your answer.

Does fixing the annotations mean switching the values such that they make sense, or is it more complicated?
i.e.
```
        if x2<=x1: x1,x2=x2,x1
        if y2>=y1: y1,y2=y2,y1
```

I also have another quick question:
How many RAM on GPU is necessary to run your algorithm?
I just tried it on a 1080 with 8GB and it ran out of memory.
Is a 2080 with 12GB or a quadro with 24GB sufficient or do I need a setup with 2GPUs?

Thank you in advance!

**Comment by leoshine** [comment]
I used to train with 2 GPUs with 12GB each.
You can of coarse adapt the batch size to fit in your GPU.
You may just need more iterations to converge.

**Comment by leoshine** [comment]
Okay.

It's fixed now.

See:

https://github.com/leoshine/Spherical_Regression/blob/e7c3b11ca327b262fbbe72947a820250354075d8/dataset/Pascal3D/prepare_data/gen_gt_box.py#L49-L72

**Comment by schellmi42** [comment]
Thank you!
