### ISSUE TITLE
Magnetic calibration

### ISSUE THREAD

**Issue by Lelelo1** [leoshine/Spherical_Regression#9]
Hello
Can this be used to calibrate magnetometer data? A uncalibrated magnetometer has soft and hard iron distortion. Soft iron creates an ellipsoid while hard iron creates an offset from origo of the measurements. Earht's magnetic field values alone forms a perfect sphere.
So I figured there might some way to predict earths magnetic field, and Spherical _Regression sound a lot like it?

**Comment by leoshine** [comment]
Interesting!  I don't have any experience with magnetometer data. But if you can somehow convert your target of prediction to a spherical target representation (e.g. S^1, S^2, S^3, etc), spherical regression may be worth to try.

**Comment by Lelelo1** [comment]
They are simply 3d vectors
[]
[.]
[..]
[...]

**Comment by Lelelo1** [comment]
Each single measurement is a Vector3. And the ideal measurements is at the surface of a sphere at origo.
In the navigation app I am doing - sequences of measurements could be collected, and constructed into ellipsoid shapes. But in the end what I am specifically looking for is to correct single measurements. 
So that the ahrs (3d orientation awareness from the north pole) of my app which uses the magnetometer of the phones - becomes more stable when navigating around with it. City environments has some magnetic disturbance in it.

There is earths magnetic field vector which is different given the geographic location - that can be looked up by an application like in my app from [wmm](https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml#igrfwmm), which is essentially a big table. All clean measurements are rotations of this vector. So i'ts length is known and can be viewed as `1` with measurements scaled down. At least that's my current understanding.

**Comment by Lelelo1** [comment]
I suspect S^2 might be it.
An ellipsoid has semi axises a, b and c . In a unit sphere they are [1, 0, 0], [0, 1, 0] and [0, 0, 1]. So that their [lengths](https://www.mathworks.com/help/matlab/ref/ellipsoid.html) are `a = 1, b = 1, c = 1`. With ellipsoid they differ, so `a = 1, b = 2, c = 1` instead. Magnetometer calibration is about finding the center of the ellipsoid of measurements, and i'ts shape (ovality) is described by a "transformation matrix". The [semi axises](https://en.wikipedia.org/wiki/Ellipsoid#Semi-axes) and [surface normal plane](https://openaccess.thecvf.com/content_CVPR_2019/papers/Liao_Spherical_Regression_Learning_Viewpoints_Surface_Normals_and_3D_Rotations_on_CVPR_2019_paper.pdf) looks almost the same to me..?

If they are the same there should be some way, maybe just subtraction is enough. (This all very speculative)

**Comment by leoshine** [comment]
This thread is closed because it is not an issue with the code. 
Feel free to continue discussion ~
